# /**
#  * Copyright (c) 2020-Present, Keita Nonaka
#  *
#  * This source code is licensed under the MIT license found in the
#  * LICENSE file in the root directory of this source tree.
#  */

[package]
name = "crate_trends_api"
version = "1.0.0"
authors = ["Keita Nonaka <iKonnyaku40@gmail.com>"]
edition = "2021"
rust-version = "1.83"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
axum = { version = "0.7.9", features = ["http2"] }
crates_io_api = "0.11"
http-body-util = "0.1.2"
serde_json = "1"
tokio = { version = "1.42.0", features = ["full"] }
tower = { version = "0.5.1", features = [
  "util", # `util` feature for unit test (oneshot func etc)
] }
tower-http = { version = "0.6.2", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
lto = true
codegen-units = 1
strip = true # same as strip command on Linux
