name: Playwright Tests
on:
  push:
    paths:
      - web/**
      - .github/workflows/playwrightCI.yml

jobs:
  e2e:
    defaults:
      run:
        working-directory: ./web
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm ci
          npm run build:wasm
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright e2e tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: npm run e2e
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: | # this doesnt take acount for working-directory
            web/e2e/playwright-report/
            web/e2e/test-results/
