name: Rust CI

on:
  push:
    paths:
      - api/**
      - .github/workflows/rustCI.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
    key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        working-directory: ./api
        run: cargo build --verbose
      - name: Run tests
        working-directory: ./api
        run: cargo test --verbose
