# /**
#  * Copyright (c) 2020-Present, Keita Nonaka
#  *
#  * This source code is licensed under the MIT license found in the
#  * LICENSE file in the root directory of this source tree.
#  */

name: Rust CI

on:
  push:
    paths:
      - api/**
      - .github/workflows/rustCI.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # with:
        #   path: |
        #     ~/.cargo/registry
        #     ~/.cargo/git
        #     target
        #   key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        working-directory: ./api
        run: cargo build --verbose
      - name: Run tests
        working-directory: ./api
        run: cargo test --verbose
